name: INDIPLEX_24_7_BOT
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update to v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Update to v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # Agar file nahi mil rahi toh manual install ka command dalo backup ke liye
        run: |
          pip install --upgrade pip
          pip install cloudscraper pymongo beautifulsoup4 certifi

      - name: Run Bot
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python scraper.py
