name: IndiPlex Scraper Bot

on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein auto-run hoga
  workflow_dispatch: # Manual run karne ke liye button dega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Permissions ke liye zaroori hai

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pymongo certifi cloudscraper

      - name: Run Scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python scraper.py

      - name: Commit and Push movies.json
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add movies.json
          # Agar koi change nahi hua toh error na de, isliye || exit 0
          git commit -m "🚀 Auto-update movies list: $(date)" || exit 0
          git push
